"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { getDataSourceConfig } from "@/lib/data-source-mode";
import { persistentApi, type ApiPart, type ApiStock } from "@/lib/persistent-api";

const PAGE_SIZE = 20;

export function PersistentPartWorkspace() {
  const config = useMemo(() => getDataSourceConfig(), []); const params = useSearchParams(); const router = useRouter();
  const [parts, setParts] = useState<ApiPart[]>([]); const [stock, setStock] = useState<ApiStock[]>([]); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  const query = params.get("q") ?? ""; const status = params.get("status") ?? "all"; const sort = params.get("sort") ?? "partNumber"; const page = Math.max(1, Number(params.get("page") ?? 1)); const selectedId = params.get("id");
  useEffect(() => { if (config.mode !== "persistent-api") return; setLoading(true); setError(null); Promise.all([persistentApi.listParts(config), persistentApi.listStock(config)]).then(([nextParts, nextStock]) => { setParts(nextParts); setStock(nextStock); }).catch((cause) => { setParts([]); setStock([]); setError(cause instanceof Error ? cause.message : "Part service unavailable."); }).finally(() => setLoading(false)); }, [config]);
  const rows = useMemo(() => parts.filter((part) => (!query || [part.partNumber, part.normalizedPartNumber, part.description, part.manufacturer, part.ata, ...(part.aircraft ?? []), ...part.alternates].some((value) => value?.toLowerCase().includes(query.toLowerCase()))) && (status === "all" || part.status === status)).sort((a, b) => sort === "updated" ? b.updatedAt.localeCompare(a.updatedAt) : sort === "manufacturer" ? (a.manufacturer ?? "").localeCompare(b.manufacturer ?? "") : a.partNumber.localeCompare(b.partNumber)), [parts, query, sort, status]);
  const selected = parts.find((part) => part.id === selectedId); const totalPages = Math.max(1, Math.ceil(rows.length / PAGE_SIZE)); const paged = rows.slice((Math.min(page, totalPages) - 1) * PAGE_SIZE, Math.min(page, totalPages) * PAGE_SIZE);
  function setParam(key: string, value: string) { const next = new URLSearchParams(params.toString()); if (value) next.set(key, value); else next.delete(key); if (key !== "page") next.set("page", "1"); router.replace(`/parts/?${next}`); }
  if (loading) return <div className="mt-4 rounded border border-border p-6 text-sm text-muted">Loading persistent Parts…</div>;
  if (error) return <div className="mt-4 rounded border border-[oklch(0.74_0.17_25)] p-4 text-sm"><p>{error}</p><button className="mt-3 font-semibold text-accent" onClick={() => window.location.reload()}>Retry</button></div>;
  if (selectedId) return <div className="mt-4 space-y-4">{selected ? <><Link className="text-sm font-semibold text-accent" href="/parts/">← All Parts</Link><section className="rounded border border-border bg-panel p-5"><div className="text-xs font-semibold text-accent">Persistent PostgreSQL Part</div><h2 className="mt-2 font-mono text-2xl font-semibold">{selected.partNumber}</h2><p className="mt-2 text-sm text-muted">{selected.description}</p><dl className="mt-5 grid gap-4 md:grid-cols-3">{[["Normalized PN", selected.normalizedPartNumber], ["Manufacturer", selected.manufacturer ?? "—"], ["Status", selected.status], ["ATA", selected.ata ?? "—"], ["IPC", selected.ipc ?? "—"], ["Aircraft", selected.aircraft?.join(", ") || "—"], ["Alternates", selected.alternates.join(", ") || "—"], ["Legacy reference", selected.legacyId ?? "Not imported"], ["Linked Stock", String(stock.filter((item) => item.partId === selected.id).length)]].map(([label, value]) => <div key={label}><dt className="text-xs text-muted">{label}</dt><dd className="mt-1 text-sm font-semibold">{value}</dd></div>)}</dl></section><section className="rounded border border-border bg-panel p-4 text-sm text-muted">RFQ, Quotes, PO, SO and Documents are workflow boundaries and contain no fixture rows. Legacy stock migration has not been completed.</section></> : <div className="rounded border border-border p-5">Part not found in the current tenant. <Link className="text-accent" href="/parts/">Return to Parts</Link></div>}</div>;
  return <div className="mt-4 space-y-3"><div className="grid gap-2 rounded border border-border bg-panel p-3 md:grid-cols-[1fr_180px_180px_auto]"><input aria-label="Search Parts" className="h-10 rounded border border-border bg-background px-3" placeholder="PN, manufacturer, ATA, aircraft, alternate…" value={query} onChange={(event) => setParam("q", event.target.value)} /><select aria-label="Part status" className="h-10 rounded border border-border bg-background px-2" value={status} onChange={(event) => setParam("status", event.target.value)}><option value="all">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select><select aria-label="Sort Parts" className="h-10 rounded border border-border bg-background px-2" value={sort} onChange={(event) => setParam("sort", event.target.value)}><option value="partNumber">PN</option><option value="manufacturer">Manufacturer</option><option value="updated">Recently updated</option></select><button className="h-10 rounded border border-border px-3" onClick={() => router.replace("/parts/")}>Reset</button></div>{paged.length ? <div className="overflow-x-auto rounded border border-border"><table className="w-full text-left text-sm"><thead className="bg-panel-muted text-xs text-muted"><tr><th className="p-3">PN</th><th>Description</th><th>Manufacturer</th><th>Status</th><th>Stock</th><th>Source</th></tr></thead><tbody>{paged.map((part) => <tr className="border-t border-border" key={part.id}><td className="p-3"><Link className="font-mono font-semibold text-accent" href={`/parts/?id=${encodeURIComponent(part.id)}`}>{part.partNumber}</Link></td><td>{part.description}</td><td>{part.manufacturer ?? "—"}</td><td>{part.status}</td><td>{stock.filter((item) => item.partId === part.id).length}</td><td>{part.legacyId ? "Imported" : "Manual/staging"}</td></tr>)}</tbody></table></div> : <div className="rounded border border-border p-6 text-sm text-muted">No persistent Parts match these filters.</div>}<div className="flex items-center justify-between text-sm"><span>{rows.length} Parts · page {Math.min(page, totalPages)} of {totalPages}</span><div className="flex gap-2"><button disabled={page <= 1} onClick={() => setParam("page", String(page - 1))}>Previous</button><button disabled={page >= totalPages} onClick={() => setParam("page", String(page + 1))}>Next</button></div></div></div>;
}
