"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { getDataSourceConfig } from "@/lib/data-source-mode";
import { persistentApi, type ApiPart, type ApiStock } from "@/lib/persistent-api";

const PAGE_SIZE = 20;

export function PersistentStockWorkspace() {
  const config = useMemo(() => getDataSourceConfig(), []); const params = useSearchParams(); const router = useRouter(); const [stock, setStock] = useState<ApiStock[]>([]); const [parts, setParts] = useState<ApiPart[]>([]); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  const query = params.get("q") ?? ""; const status = params.get("status") ?? "all"; const quantity = params.get("quantity") ?? "all"; const sort = params.get("sort") ?? "updated"; const page = Math.max(1, Number(params.get("page") ?? 1)); const selectedId = params.get("id");
  useEffect(() => { if (config.mode !== "persistent-api") return; Promise.all([persistentApi.listStock(config), persistentApi.listParts(config)]).then(([items, nextParts]) => { setStock(items); setParts(nextParts); }).catch((cause) => { setStock([]); setParts([]); setError(cause instanceof Error ? cause.message : "Stock service unavailable."); }).finally(() => setLoading(false)); }, [config]);
  const partById = useMemo(() => new Map(parts.map((part) => [part.id, part])), [parts]);
  const rows = useMemo(() => stock.filter((item) => { const part = partById.get(item.partId); return (!query || [part?.partNumber, item.serialNumber, item.condition, item.releaseType, item.locationText].some((value) => value?.toLowerCase().includes(query.toLowerCase()))) && (status === "all" || item.status === status) && (quantity === "all" || (quantity === "zero" ? item.quantity === 0 : item.quantity > 0)); }).sort((a, b) => sort === "quantity" ? b.quantity - a.quantity : sort === "part" ? (partById.get(a.partId)?.partNumber ?? "").localeCompare(partById.get(b.partId)?.partNumber ?? "") : b.updatedAt.localeCompare(a.updatedAt)), [partById, query, quantity, sort, status, stock]);
  const selected = stock.find((item) => item.id === selectedId); const selectedPart = selected ? partById.get(selected.partId) : undefined; const totalPages = Math.max(1, Math.ceil(rows.length / PAGE_SIZE)); const paged = rows.slice((Math.min(page, totalPages) - 1) * PAGE_SIZE, Math.min(page, totalPages) * PAGE_SIZE);
  function setParam(key: string, value: string) { const next = new URLSearchParams(params.toString()); if (value) next.set(key, value); else next.delete(key); if (key !== "page") next.set("page", "1"); router.replace(`/stock/internal/?${next}`); }
  if (loading) return <div className="mt-4 rounded border border-border p-6 text-sm text-muted">Loading persistent Stock…</div>;
  if (error) return <div className="mt-4 rounded border border-[oklch(0.74_0.17_25)] p-4 text-sm"><p>{error}</p><button className="mt-3 font-semibold text-accent" onClick={() => window.location.reload()}>Retry</button></div>;
  if (selectedId) return <div className="mt-4 space-y-4">{selected ? <><Link className="text-sm font-semibold text-accent" href="/stock/internal/">← All Stock</Link><section className="rounded border border-border bg-panel p-5"><div className="text-xs font-semibold text-accent">Persistent PostgreSQL Stock</div><h2 className="mt-2 font-mono text-2xl font-semibold">{selectedPart?.partNumber ?? selected.partId}{selected.serialNumber ? ` / ${selected.serialNumber}` : ""}</h2><dl className="mt-5 grid gap-4 md:grid-cols-3">{[["Quantity", String(selected.quantity)], ["Condition", selected.condition ?? "—"], ["Release", selected.releaseType ?? "—"], ["Status", selected.status], ["Location", selected.locationText ?? "—"], ["Owner Company ID", selected.ownerCompanyId ?? "—"], ["Supplier Company ID", selected.supplierCompanyId ?? "—"], ["Tag-info Company ID", selected.tagInfoCompanyId ?? "—"], ["Traceability Company ID", selected.traceabilityCompanyId ?? "—"], ["Source", selected.legacyId ? "Imported" : "Manual/staging"], ["Legacy reference", selected.legacyId ?? "Not imported"]].map(([label, value]) => <div key={label}><dt className="text-xs text-muted">{label}</dt><dd className="mt-1 text-sm font-semibold">{value}</dd></div>)}</dl></section><section className="rounded border border-border bg-panel p-4 text-sm text-muted">Legacy stock migration not yet completed. Documents, RFQ, Quotes, PO, SO, repair, exchange and lease are workflow boundaries; no fixture records are shown.</section></> : <div className="rounded border border-border p-5">Stock item not found in the current tenant. <Link className="text-accent" href="/stock/internal/">Return to Stock</Link></div>}</div>;
  return <div className="mt-4 space-y-3"><div className="rounded border border-[oklch(0.8_0.12_80)] bg-panel p-3 text-sm">Legacy stock migration not yet completed. Rows below are only persistent staging/manual records unless explicitly marked imported.</div><div className="grid gap-2 rounded border border-border bg-panel p-3 lg:grid-cols-[1fr_150px_150px_170px_auto]"><input aria-label="Search Stock" className="h-10 rounded border border-border bg-background px-3" placeholder="PN, serial, condition, release, location…" value={query} onChange={(event) => setParam("q", event.target.value)} /><select aria-label="Stock status" value={status} onChange={(event) => setParam("status", event.target.value)}><option value="all">All statuses</option>{[...new Set(stock.map((item) => item.status))].sort().map((value) => <option key={value}>{value}</option>)}</select><select aria-label="Stock quantity" value={quantity} onChange={(event) => setParam("quantity", event.target.value)}><option value="all">All quantities</option><option value="positive">Qty above zero</option><option value="zero">Qty zero</option></select><select aria-label="Sort Stock" value={sort} onChange={(event) => setParam("sort", event.target.value)}><option value="updated">Recently updated</option><option value="part">PN</option><option value="quantity">Quantity</option></select><button className="h-10 rounded border border-border px-3" onClick={() => router.replace("/stock/internal/")}>Reset</button></div>{paged.length ? <div className="overflow-x-auto rounded border border-border"><table className="w-full text-left text-sm"><thead className="bg-panel-muted text-xs text-muted"><tr><th className="p-3">PN</th><th>Serial</th><th>Qty</th><th>Condition</th><th>Status</th><th>Location</th><th>Source</th></tr></thead><tbody>{paged.map((item) => <tr className="border-t border-border" key={item.id}><td className="p-3"><Link className="font-mono font-semibold text-accent" href={`/stock/internal/?id=${encodeURIComponent(item.id)}`}>{partById.get(item.partId)?.partNumber ?? item.partId}</Link></td><td>{item.serialNumber ?? "—"}</td><td>{item.quantity}</td><td>{item.condition ?? "—"}</td><td>{item.status}</td><td>{item.locationText ?? "—"}</td><td>{item.legacyId ? "Imported" : "Manual/staging"}</td></tr>)}</tbody></table></div> : <div className="rounded border border-border p-6 text-sm text-muted">No persistent Stock matches these filters.</div>}<div className="flex items-center justify-between text-sm"><span>{rows.length} Stock rows · page {Math.min(page, totalPages)} of {totalPages}</span><div className="flex gap-2"><button disabled={page <= 1} onClick={() => setParam("page", String(page - 1))}>Previous</button><button disabled={page >= totalPages} onClick={() => setParam("page", String(page + 1))}>Next</button></div></div></div>;
}
